//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperRate
    {
        public int PaperRateID { get; set; }
        public Nullable<int> GSMID { get; set; }
        public Nullable<int> PaperSizeID { get; set; }
        public Nullable<decimal> Paperlength { get; set; }
        public Nullable<decimal> PaperWidth { get; set; }
        public Nullable<int> PaperTypeID { get; set; }
        public Nullable<int> PaperManufaturerID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> AddEditBy { get; set; }
        public Nullable<System.DateTime> AddEditOn { get; set; }
    }
}
