//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintRateCalculation
    {
        public long PrintRateID { get; set; }
        public Nullable<int> CuttingSizeID { get; set; }
        public Nullable<int> PlateID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<decimal> PlateCost1K { get; set; }
        public Nullable<decimal> ColorCost1K { get; set; }
        public Nullable<decimal> PlateCost10K { get; set; }
        public Nullable<decimal> ColorCost10K { get; set; }
        public string RecMode { get; set; }
        public Nullable<int> UploadBy { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
    }
}
