//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintingParameter
    {
        public int PrintingParameterID { get; set; }
        public Nullable<int> PrintingParameterTypeID { get; set; }
        public string PrintingParameterName { get; set; }
        public string PrintingParameterDescription { get; set; }
        public Nullable<decimal> ParameterValue1 { get; set; }
        public Nullable<decimal> ParameterValue2 { get; set; }
        public Nullable<decimal> ParameterValue3 { get; set; }
        public Nullable<decimal> ParameterValue4 { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public string RecMode { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LMB { get; set; }
        public Nullable<System.DateTime> LMD { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    }
}
