//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationJobSheetDetail
    {
        public long QuotationJobSheetDetailID { get; set; }
        public Nullable<long> QuotationID { get; set; }
        public Nullable<int> PrintComponentID { get; set; }
        public Nullable<int> NoOfSheet { get; set; }
        public Nullable<int> GSMID { get; set; }
        public Nullable<int> GSMValue { get; set; }
        public Nullable<int> PaperSizeID { get; set; }
        public Nullable<decimal> PaperLength { get; set; }
        public Nullable<decimal> PaperWidth { get; set; }
        public Nullable<int> PaperTypeID { get; set; }
        public Nullable<int> PaperManufaturerID { get; set; }
        public Nullable<int> NoOfSheetPrintDetail { get; set; }
        public Nullable<int> PaperSizeIDPrintDetail { get; set; }
        public Nullable<decimal> Impression { get; set; }
        public Nullable<int> CuttingID { get; set; }
        public Nullable<int> NoofCuttingPices { get; set; }
        public Nullable<decimal> FinishSize { get; set; }
        public Nullable<int> SideID { get; set; }
        public Nullable<int> ColourID { get; set; }
        public Nullable<int> PlateTypeID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<int> FabricationItemID { get; set; }
        public string FabricationItemSize { get; set; }
        public Nullable<int> PackagingItemID { get; set; }
        public Nullable<decimal> LabourCharge { get; set; }
        public Nullable<decimal> TransportCharge { get; set; }
        public Nullable<int> TransportUnitID { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> LineQuantity { get; set; }
        public Nullable<decimal> LineRate { get; set; }
        public Nullable<decimal> LineAmount { get; set; }
        public Nullable<decimal> LineGST { get; set; }
    }
}
