//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationJobSheet
    {
        public long QuotationID { get; set; }
        public string QuotationNO { get; set; }
        public Nullable<System.DateTime> QuotationDate { get; set; }
        public Nullable<bool> IS_JOB { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<decimal> GSTPercentage { get; set; }
        public Nullable<decimal> GSTWOPaper { get; set; }
        public Nullable<decimal> CGSTAmount { get; set; }
        public Nullable<decimal> SGSTAmount { get; set; }
        public Nullable<decimal> IGSTAmount { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<decimal> TotalBillingAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> RoundOff { get; set; }
        public Nullable<decimal> AmountPayable { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> OutstandingAmount { get; set; }
        public string Remarks { get; set; }
        public string FinYear { get; set; }
        public string RecMode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> LMB { get; set; }
        public Nullable<System.DateTime> LMD { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
