//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
        public string Nane { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsSystemPermission { get; set; }
        public Nullable<bool> IsUserPermission { get; set; }
        public string RecMode { get; set; }
        public Nullable<int> AddEditBy { get; set; }
        public Nullable<System.DateTime> AddEditOn { get; set; }
    }
}
